server:
  port: 9298

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SerdarBrk/config-server
          clone-on-start: true