server:
  port: 9005

spring:
  application:
    name: TRANSFER-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/

ribbon:
  eager-load:
    enabled: true
    clients: exchangerates
  http:
    client:
      enabled: true
exchangerates:
  ribbon:
    listOfServers: http://api.exchangeratesapi.io/
    ServerListRefreshInterval: 15000